# Your Solution
version: '3'
services:

  book-catalog:
    image: book-catalog:1
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=$DB_URL
    restart: "no"

  inventory-management:
    image: inventory-management:1
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8002:8002"
    environment:
      - PORT=8002
      - DATABASE_URL=$DB_URL
    restart: "no"
